TestCaseDynamoDBTable:
  Type: "AWS::DynamoDB::Table"
  Properties:
    AttributeDefinitions:
      - AttributeName: testCaseId
        AttributeType: S
      - AttributeName: userId
        AttributeType: S
    KeySchema:
      - AttributeName: testCaseId
        KeyType: HASH
      - AttributeName: userId
        KeyType: RANGE
    BillingMode: PAY_PER_REQUEST
    TableName: ${self:provider.environment.TESTCASE_TABLE}
    GlobalSecondaryIndexes:
      - IndexName: ${self:provider.environment.TESTCASE_USER_INDEX}
        KeySchema:
        - AttributeName: userId
          KeyType: HASH
        Projection:
          ProjectionType: ALL
